-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 16:41:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `idPersonne` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL DEFAULT check(idCompany > 0),
  `nomsocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personne_has_Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne_has_Company` (
  `Personne_idPersonne` INT NOT NULL,
  `Company_idCompany` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`, `Company_idCompany`),
  INDEX `fk_Personne_has_Company_Company1_idx` (`Company_idCompany` ASC),
  INDEX `fk_Personne_has_Company_Personne_idx` (`Personne_idPersonne` ASC),
  CONSTRAINT `fk_Personne_has_Company_Personne`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `mydb`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personne_has_Company_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
