/* Le code UNITE et QUALIF dans la table POSTE doivent exister dans 
les tables UNITE et QUALIF
*/

ALTER TABLE postes ADD CONSTRAINT FK_POSTE_UNITCOD FOREIGN KEY (UNITCOD) REFERENCES unite(UNITCOD);
ALTER TABLE postes ADD CONSTRAINT FK_POSTE_CODQUALIF FOREIGN KEY (CODQUALIF) REFERENCES qualif(CODQUALIF);

